import { EXERCISE_BY_SLUG } from '../data/exerciseCatalog';
import type { GeneratedPlan, PlanDay } from '../types/database';

/**
 * Generated-plan sync core (B-19) — PURE mapping + direction helpers (node-testable,
 * no supabase/store imports). Conflict policy: LOCAL WINS. The local generated
 * plan is never mutated or regenerated by these functions.
 */

export type PlanSyncDirection = 'push' | 'pull' | 'noop';

/** Local-wins: local plan present → push (even if remote exists); else pull; else noop. */
export function decidePlanSyncDirection(localHasPlan: boolean, remoteHasPlan: boolean): PlanSyncDirection {
  if (localHasPlan) return 'push';
  if (remoteHasPlan) return 'pull';
  return 'noop';
}

// ---- push mapping: GeneratedPlan → DB rows (subset of DATA_MODEL columns) ----

export interface PlanRow {
  user_id: string;
  title: string;
  weeks: number;
  start_date: string | null;
  status: 'active';
  current_week: number;
}

export interface DayRow {
  plan_id: string;
  week_number: number;
  day_number: number;
  focus: PlanDay['focus'];
  duration_min: number;
  habit_goal: string | null;
}

export interface ExerciseRow {
  workout_day_id: string;
  exercise_id: string; // remote exercises.id (uuid), resolved from local slug
  order_index: number;
  sets: number;
  rep_min: number;
  rep_max: number;
  suggested_weight_lb: number | null;
  rest_seconds: number;
}

export function toPlanRow(plan: GeneratedPlan, userId: string): PlanRow {
  return {
    user_id: userId,
    title: plan.title,
    weeks: plan.weeks,
    start_date: null,
    status: 'active',
    current_week: 1,
  };
}

export function toDayRow(day: PlanDay, planId: string): DayRow {
  return {
    plan_id: planId,
    week_number: day.weekNumber,
    day_number: day.dayNumber,
    focus: day.focus,
    duration_min: day.estimatedMinutes,
    habit_goal: null,
  };
}

/**
 * Map a day's strength exercises to workout_exercises rows. `slugToId` resolves
 * the local slug to the remote `exercises.id` (uuid). Any slug not present remotely
 * is reported in `missingSlugs` so the caller can STOP (schema/seed mismatch) rather
 * than write a broken FK.
 */
export function toExerciseRows(
  day: PlanDay,
  workoutDayId: string,
  slugToId: Record<string, string>,
): { rows: ExerciseRow[]; missingSlugs: string[] } {
  const rows: ExerciseRow[] = [];
  const missingSlugs: string[] = [];
  day.strength.forEach((ex, i) => {
    const exerciseId = slugToId[ex.slug];
    if (!exerciseId) {
      missingSlugs.push(ex.slug);
      return;
    }
    rows.push({
      workout_day_id: workoutDayId,
      exercise_id: exerciseId,
      order_index: i,
      sets: ex.sets,
      rep_min: ex.repMin,
      rep_max: ex.repMax,
      suggested_weight_lb: EXERCISE_BY_SLUG[ex.slug]?.defaultWeightLb ?? null,
      rest_seconds: ex.restSeconds,
    });
  });
  return { rows, missingSlugs };
}

/**
 * PULL is DEFERRED this loop (documented schema gap): workout_days/workout_exercises
 * do NOT store the full local plan view (cardio block, day name, beginner note,
 * guidance text, estimated minutes are lost), and regenerating during sync is
 * forbidden (req 11). So a faithful local plan cannot be reconstructed and we do
 * not apply a pull. See docs/GENERATED_PLAN_SYNC_REVIEW.md §Pull.
 */
export const PLAN_PULL_SUPPORTED = false;
